// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/book_core.dart';

Future<void> helloWorld() => Rc.instance.api.crateApiHelloWorld();

Future<MetaData> getCodeMetadata({required String code}) =>
    Rc.instance.api.crateApiGetCodeMetadata(code: code);

Future<String> runCoreAction({
  required String code,
  required String action,
  required String envs,
}) => Rc.instance.api.crateApiRunCoreAction(
  code: code,
  action: action,
  envs: envs,
);

Future<List<SearchBook>> coreSearchBooks({
  required String code,
  required String key,
  required int page,
  required int count,
}) => Rc.instance.api.crateApiCoreSearchBooks(
  code: code,
  key: key,
  page: page,
  count: count,
);

Future<BookDetail> coreBookDetail({
  required String code,
  required String bid,
}) => Rc.instance.api.crateApiCoreBookDetail(code: code, bid: bid);

Future<List<CatalogVolume>> coreCatalog({
  required String code,
  required String bid,
}) => Rc.instance.api.crateApiCoreCatalog(code: code, bid: bid);

Future<Chapter> coreChapter({
  required String code,
  required String bid,
  required String cid,
}) => Rc.instance.api.crateApiCoreChapter(code: code, bid: bid, cid: cid);
