// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> helloWorld() => Rc.instance.api.crateApiHelloWorld();

Future<String> getCodeMetadata({required String code}) =>
    Rc.instance.api.crateApiGetCodeMetadata(code: code);

Future<Value> runCoreAction({
  required String code,
  required String action,
  required Value envs,
}) => Rc.instance.api.crateApiRunCoreAction(
  code: code,
  action: action,
  envs: envs,
);

Future<Value> coreSearchBooks({
  required String code,
  required String keyword,
  required int page,
  required int count,
}) => Rc.instance.api.crateApiCoreSearchBooks(
  code: code,
  keyword: keyword,
  page: page,
  count: count,
);

Future<Value> coreBookDetail({required String code, required String bid}) =>
    Rc.instance.api.crateApiCoreBookDetail(code: code, bid: bid);

Future<Value> coreCatalog({required String code, required String bid}) =>
    Rc.instance.api.crateApiCoreCatalog(code: code, bid: bid);

Future<Value> coreChapter({
  required String code,
  required String bid,
  required String cid,
}) => Rc.instance.api.crateApiCoreChapter(code: code, bid: bid, cid: cid);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Value>>
abstract class Value implements RustOpaqueInterface {}
