// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> helloWorld() => Rc.instance.api.crateApiHelloWorld();

Future<BookCore> initBookCore({required String code}) =>
    Rc.instance.api.crateApiInitBookCore(code: code);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BookCore>>
abstract class BookCore implements RustOpaqueInterface {
  Future<JsResultJsValue> callFunc({
    required String func,
    required List<Value> args,
  });

  Future<void> clearEnvs();

  Future<String> eval({required String code});

  Future<String> getActions();

  Future<Value> getBookDetail({required String bid});

  Future<Value> getCatalog({required String bid});

  Future<Value> getChapter({required String bid, required String cid});

  Future<Value> getEnv({required String key});

  Future<Value> getEnvs();

  Future<String> getForms();

  Future<String> getMetadata();

  static Future<BookCore> init({required String code}) =>
      Rc.instance.api.crateApiBookCoreInit(code: code);

  Future<String> runAction({required String action});

  Future<Value> searchBooks({
    required String keyword,
    required int page,
    required int count,
  });

  Future<void> setEnv({required String key, required Value value});

  Future<void> setEnvs({required Value envs});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JsResult < JsValue >>>
abstract class JsResultJsValue implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Value>>
abstract class Value implements RustOpaqueInterface {}
