// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'third_party/book_core.dart';

abstract class RcApiImplPlatform extends BaseApiImpl<RcWire> {
  RcApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BookDetail dco_decode_book_detail(dynamic raw);

  @protected
  BookExtraData dco_decode_book_extra_data(dynamic raw);

  @protected
  BookLatestChapter dco_decode_book_latest_chapter(dynamic raw);

  @protected
  BookStatus dco_decode_book_status(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BookLatestChapter dco_decode_box_autoadd_book_latest_chapter(dynamic raw);

  @protected
  BookStatus dco_decode_box_autoadd_book_status(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  Proxy dco_decode_box_autoadd_proxy(dynamic raw);

  @protected
  ProxyType dco_decode_box_autoadd_proxy_type(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CatalogChapter dco_decode_catalog_chapter(dynamic raw);

  @protected
  CatalogVolume dco_decode_catalog_volume(dynamic raw);

  @protected
  Chapter dco_decode_chapter(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BookExtraData> dco_decode_list_book_extra_data(dynamic raw);

  @protected
  List<CatalogChapter> dco_decode_list_catalog_chapter(dynamic raw);

  @protected
  List<CatalogVolume> dco_decode_list_catalog_volume(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SearchBook> dco_decode_list_search_book(dynamic raw);

  @protected
  MetaData dco_decode_meta_data(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BookLatestChapter? dco_decode_opt_box_autoadd_book_latest_chapter(
    dynamic raw,
  );

  @protected
  BookStatus? dco_decode_opt_box_autoadd_book_status(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  Proxy? dco_decode_opt_box_autoadd_proxy(dynamic raw);

  @protected
  ProxyType? dco_decode_opt_box_autoadd_proxy_type(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<BookExtraData>? dco_decode_opt_list_book_extra_data(dynamic raw);

  @protected
  Proxy dco_decode_proxy(dynamic raw);

  @protected
  ProxyType dco_decode_proxy_type(dynamic raw);

  @protected
  SearchBook dco_decode_search_book(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BookDetail sse_decode_book_detail(SseDeserializer deserializer);

  @protected
  BookExtraData sse_decode_book_extra_data(SseDeserializer deserializer);

  @protected
  BookLatestChapter sse_decode_book_latest_chapter(
    SseDeserializer deserializer,
  );

  @protected
  BookStatus sse_decode_book_status(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BookLatestChapter sse_decode_box_autoadd_book_latest_chapter(
    SseDeserializer deserializer,
  );

  @protected
  BookStatus sse_decode_box_autoadd_book_status(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  Proxy sse_decode_box_autoadd_proxy(SseDeserializer deserializer);

  @protected
  ProxyType sse_decode_box_autoadd_proxy_type(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CatalogChapter sse_decode_catalog_chapter(SseDeserializer deserializer);

  @protected
  CatalogVolume sse_decode_catalog_volume(SseDeserializer deserializer);

  @protected
  Chapter sse_decode_chapter(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BookExtraData> sse_decode_list_book_extra_data(
    SseDeserializer deserializer,
  );

  @protected
  List<CatalogChapter> sse_decode_list_catalog_chapter(
    SseDeserializer deserializer,
  );

  @protected
  List<CatalogVolume> sse_decode_list_catalog_volume(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SearchBook> sse_decode_list_search_book(SseDeserializer deserializer);

  @protected
  MetaData sse_decode_meta_data(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BookLatestChapter? sse_decode_opt_box_autoadd_book_latest_chapter(
    SseDeserializer deserializer,
  );

  @protected
  BookStatus? sse_decode_opt_box_autoadd_book_status(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  Proxy? sse_decode_opt_box_autoadd_proxy(SseDeserializer deserializer);

  @protected
  ProxyType? sse_decode_opt_box_autoadd_proxy_type(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<BookExtraData>? sse_decode_opt_list_book_extra_data(
    SseDeserializer deserializer,
  );

  @protected
  Proxy sse_decode_proxy(SseDeserializer deserializer);

  @protected
  ProxyType sse_decode_proxy_type(SseDeserializer deserializer);

  @protected
  SearchBook sse_decode_search_book(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_book_detail(BookDetail self, SseSerializer serializer);

  @protected
  void sse_encode_book_extra_data(BookExtraData self, SseSerializer serializer);

  @protected
  void sse_encode_book_latest_chapter(
    BookLatestChapter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_book_status(BookStatus self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book_latest_chapter(
    BookLatestChapter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_book_status(
    BookStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_proxy(Proxy self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_proxy_type(
    ProxyType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_catalog_chapter(
    CatalogChapter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_catalog_volume(CatalogVolume self, SseSerializer serializer);

  @protected
  void sse_encode_chapter(Chapter self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_book_extra_data(
    List<BookExtraData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_catalog_chapter(
    List<CatalogChapter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_catalog_volume(
    List<CatalogVolume> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_book(
    List<SearchBook> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meta_data(MetaData self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_book_latest_chapter(
    BookLatestChapter? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_book_status(
    BookStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_proxy(Proxy? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_proxy_type(
    ProxyType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_book_extra_data(
    List<BookExtraData>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy(Proxy self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_type(ProxyType self, SseSerializer serializer);

  @protected
  void sse_encode_search_book(SearchBook self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RcWire implements BaseWire {
  RcWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RcWasmModule get wasmModule;

@JS()
@anonymous
extension type RcWasmModule._(JSObject _) implements JSObject {}
