// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Map<String, String> getEnv({required String uuid}) =>
    Rc.instance.api.crateApiEnvsGetEnv(uuid: uuid);

void setEnv({required String uuid, required Map<String, String> value}) =>
    Rc.instance.api.crateApiEnvsSetEnv(uuid: uuid, value: value);
