name: use_case
description: 'Usecase for models.'
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
