// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String jsEval({required String code}) =>
    RustLib.instance.api.crateApiEcmaJsEval(code: code);

Future<String> jsEvalAsync({required String code}) =>
    RustLib.instance.api.crateApiEcmaJsEvalAsync(code: code);

Future<String> jsEvalAuto({required String code}) =>
    RustLib.instance.api.crateApiEcmaJsEvalAuto(code: code);

Future<String> jsAction(
        {required String uuid, required String method, required String args}) =>
    RustLib.instance.api
        .crateApiEcmaJsAction(uuid: uuid, method: method, args: args);

String jsGetAttribute({required String uuid, required String key}) =>
    RustLib.instance.api.crateApiEcmaJsGetAttribute(uuid: uuid, key: key);

Map<String, String> jsGetAttributes(
        {required String uuid, required List<String> keys}) =>
    RustLib.instance.api.crateApiEcmaJsGetAttributes(uuid: uuid, keys: keys);

void initJsScripts({required Map<String, String> scripts}) =>
    RustLib.instance.api.crateApiEcmaInitJsScripts(scripts: scripts);

void insertJsScript({required String uuid, required String code}) =>
    RustLib.instance.api.crateApiEcmaInsertJsScript(uuid: uuid, code: code);

void removeJsScript({required String uuid}) =>
    RustLib.instance.api.crateApiEcmaRemoveJsScript(uuid: uuid);

String getUuid({required String code}) =>
    RustLib.instance.api.crateApiEcmaGetUuid(code: code);
